#!/bin/sh

# This supports stdin and pipes by the way, the options should be separated by newline characters.
# For example: 
#
# echo "SSID
# y
# 2
# password" | wifiqr

# QR Code is a registered trademark of DENSO WAVE INCORPORATED in the United States and other countries.

echo "Wi-Fi SSID (Network name)"
read ssidInput
ssid=$(echo ${ssidInput} | sed -e 's/\\/\\\\/g' -e 's/;/\\;/g' -e 's/,/\\,/g' -e 's/:/\\:/g' -e 's/"/\\"/g')

read -p "Is Wi-Fi SSID hidden [y, N] (if you don't know it's probably not hidden) " hiddenInput

cat <<- EOF
Which encryption do you have (if you don't know it's probably WPA/WPA2)
  1) WPA/WPA2
  2) WEP
  3) None
Type the number of the correct option:
EOF
read encryptionn

case $encryptionn in
  1) encryption=WPA ;;
  2) encryption=WEP ;;
  3) encryption=nopass ;;
  *) echo "You didn't provide a valid encryption."; exit 1;;
esac
[ "$encryption" != "nopass" ] && read -p "Wi-Fi Password (leave blank for open network) " passwordInput
password=$(echo ${passwordInput} | sed -e 's/\\/\\\\/g' -e 's/;/\\;/g' -e 's/,/\\,/g' -e 's/:/\\:/g' -e 's/"/\\"/g')

case $hiddenInput in
  y|Y) hidden=true ;;
  n|N) hidden=false ;;
  *) hidden=false ;;
esac

qrstring="WIFI:S:${ssid};T:${encryption};P:${password};H:${hidden};"
filepath=$(echo $1 | cut -d "=" -f2)
echo $filepath

if [ -z $filepath ];
then
  echo $qrstring | qr;
else
  echo $qrstring | qr > $filepath
fi
