#!/bin/sh

# This supports stdin and pipes by the way, the options should be separated by newline characters.
# For example: 
#
# echo "SSID
# y
# 2
# password" | wifiqr

# QR Code is a registered trademark of DENSO WAVE INCORPORATED in the United States and other countries.

echo "Wi-Fi SSID (Network name)"
read ssidInput
# There totally is a better way of doing this but I'm a complete idiot and I didn't have time
# to research the better way
ssid=$(echo ${ssidInput} | sed 's/\\/\\\\/g')
ssid=$(echo ${ssid} | sed 's/;/\\;/g')
ssid=$(echo ${ssid} | sed 's/,/\\,/g')
ssid=$(echo ${ssid} | sed 's/:/\\:/g')
ssid=$(echo ${ssid} | sed 's/"/\\"/g')

read -p "Is Wi-Fi SSID hidden [y, N] (if you don't know it's probably not hidden) " hiddenInput

echo "Which encryption do you have (if you don't know it's probably WPA/WPA2)"
echo "  1) WPA/WPA2"
echo "  2) WEP"
echo "  3) None"
echo "Type the number of the correct option: "
read encryptionn

case $encryptionn in
  1) encryption=WPA ;;
  2) encryption=WEP ;;
  3) encryption=nopass ;;
  *) echo "You didn't provide a valid encryption."; exit 1;;
esac
[ "$encryption" != "nopass" ] && read -p "Wi-Fi Password (leave blank for open network) " passwordInput
# There totally is a better way of doing this but I'm a complete idiot and I didn't have time
# to research the better way
password=$(echo ${passwordInput} | sed 's/\\/\\\\/g')
password=$(echo ${password} | sed 's/;/\\;/g')
password=$(echo ${password} | sed 's/,/\\,/g')
password=$(echo ${password} | sed 's/:/\\:/g')
password=$(echo ${password} | sed 's/"/\\"/g')

case $hiddenInput in
  y|Y) hidden=true ;;
  n|N) hidden=false ;;
  *) hidden=false ;;
esac

qrstring="WIFI:S:${ssid};T:${encryption};P:${password};H:${hidden};"
filepath=$(echo $1 | cut -d "=" -f2)
echo $filepath

if [ -z $filepath ];
then
  echo $qrstring | qr;
else
  echo $qrstring | qr > $filepath
fi
